name: "Network"
version: "1.0"

channels:
  airlinechannel:
    orderers:
      - orderer.acme.com
    peers:
      acme-peer1.acme.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      budget-peer1.budget.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false

organizations:
  Acme:
    mspid: AcmeMSP
    peers:
      - acme-peer1.acme.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: ../crypto/crypto-config/peerOrganizations/acme.com/users/Admin@acme.com/msp/keystore/e0e1ec4237fd02daae6699f53b5d485615bef5b57ec519dc58a7241c08f07ed1_sk
    signedCert:
      path: ../crypto/crypto-config/peerOrganizations/acme.com/users/Admin@acme.com/msp/signcerts/Admin@acme.com-cert.pem

  Budget:
    mspid: BudgetMSP
    peers:
      - budget-peer1.budget.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: ../crypto/crypto-config/peerOrganizations/budget.com/users/Admin@budget.com/msp/keystore/05beac9849f610ad5cc8997e5f45343ca918de78398988def3f288b60d8ee27c_sk
    signedCert:
      path: ../crypto/crypto-config/peerOrganizations/budget.com/users/Admin@budget.com/msp/signcerts/Admin@budget.com-cert.pem

orderers:
  orderer.acme.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.acme.com
      grpc-max-send-message-length: 15
    # tlsCACerts:
    #   path: ../crypto/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tlscacerts/example.com-cert.pem

peers:
  acme-peer1.acme.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: acme-peer1.acme.com
      grpc.keepalive_time_ms: 600000
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/acme.com/peers/peer0.acme.com/tlscacerts/acme.com-cert.pem

  budget-peer1.budget.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: budget-peer1.budget.com
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/budget.com/peers/peer0.budget.com/tlscacerts/budget.com-cert.pem

certificateAuthorities:
  ca.caserver.com:
    url: http://localhost:7054
    httpOptions:
      verify: false
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/acme.com/ca/cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: caserver

